name: build-and-bundle
on: 
  pull_request:
  push:
    branches:
      - ros1
  schedule:
    - cron: '0 14 * * *'  # run at 2 pm everyday

jobs:
  build_and_bundle_robot_ws:
    strategy:
      matrix:
        distro: ['kinetic', 'melodic']
    runs-on: ubuntu-latest
    name: 'Build and Bundle robot_ws'
    container:
      image: ros:${{ matrix.distro }}-ros-core
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Build and Bundle
      id: build
      uses: mm318/aws-robomaker-sample-application-ci@master
      with:
        ros-distro: ${{ matrix.distro }}
        workspace-dir: robot_ws
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_ROS1 }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_ROS1 }}
        aws-region: us-west-2
      if: always() && github.ref == 'refs/heads/ros1'
    - name: Log Build Status
      uses: ros-tooling/action-cloudwatch-metrics@0.0.4
      with:
        namespace: 'GitHubActionsCI'
      if: always() && github.ref == 'refs/heads/ros1'
    - name: Upload to S3
      uses: mm318/s3-cp-action@v0.3.0
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_ROS1 }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_ROS1 }}
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET_ROS1 }}
        AWS_REGION: 'us-west-2'
        FILES: 'sources.zip sources.tar.gz robot_ws.tar'
        DEST: 'travis/cloudwatch/${{ steps.build.outputs.ros-distro }}/${{ steps.build.outputs.gazebo-version }}/${{ steps.build.outputs.sample-app-version }}.${{ github.run_number }}/'
      if: github.event_name == 'schedule'

  build_and_bundle_simulation_ws:
    strategy:
      matrix:
        distro: ['kinetic', 'melodic']
    runs-on: ubuntu-latest
    name: 'Build and Bundle simulation_ws'
    container:
      image: ros:${{ matrix.distro }}-ros-core
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Build and Bundle
      id: build
      uses: mm318/aws-robomaker-sample-application-ci@master
      with:
        ros-distro: ${{ matrix.distro }}
        workspace-dir: simulation_ws
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_ROS1 }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_ROS1 }}
        aws-region: us-west-2
      if: always() && github.ref == 'refs/heads/ros1'
    - name: Log Build Status
      uses: ros-tooling/action-cloudwatch-metrics@0.0.4
      with:
        namespace: 'GitHubActionsCI'
      if: always() && github.ref == 'refs/heads/ros1'
    - name: Upload to S3
      uses: mm318/s3-cp-action@v0.3.0
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_ROS1 }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_ROS1 }}
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET_ROS1 }}
        AWS_REGION: 'us-west-2'
        FILES: 'simulation_ws.tar'
        DEST: 'travis/cloudwatch/${{ steps.build.outputs.ros-distro }}/${{ steps.build.outputs.gazebo-version }}/${{ steps.build.outputs.sample-app-version }}.${{ github.run_number }}/'
      if: github.event_name == 'schedule'

  build_and_bundle_simulation_ws_kinetc_gazebo9:
    runs-on: ubuntu-latest
    name: 'Build and Bundle simulation_ws (kinetic with gazebo 9)'
    container:
      image: ros:kinetic-ros-core
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Build and Bundle
      id: build
      uses: mm318/aws-robomaker-sample-application-ci@master
      with:
        ros-distro: kinetic
        gazebo-version: 9
        workspace-dir: simulation_ws
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_ROS1 }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_ROS1 }}
        aws-region: us-west-2
      if: always() && github.ref == 'refs/heads/ros1'
    - name: Log Build Status
      uses: ros-tooling/action-cloudwatch-metrics@0.0.4
      with:
        namespace: 'GitHubActionsCI'
      if: always() && github.ref == 'refs/heads/ros1'
    - name: Upload to S3
      uses: mm318/s3-cp-action@v0.3.0
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_ROS1 }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_ROS1 }}
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET_ROS1 }}
        AWS_REGION: 'us-west-2'
        FILES: 'simulation_ws.tar'
        DEST: 'travis/cloudwatch/${{ steps.build.outputs.ros-distro }}/${{ steps.build.outputs.gazebo-version }}/${{ steps.build.outputs.sample-app-version }}.${{ github.run_number }}/'
      if: github.event_name == 'schedule'
